### ISSUE TITLE
English text in French version of http://robgungor.com/tutorial/#french_Story1_53_next_agi

### ISSUE THREAD

**Issue by MediaSmarts** [DoYourThing/CyberChoices#225]
![pixone153](https://cloud.githubusercontent.com/assets/8646341/5647159/60c234d0-9651-11e4-9ae4-9c569b188637.png)

**Comment by jmseck** [comment]
@robgungor Rob can you cover these text changes or do I need to make these revisions?

**Comment by robgungor** [comment]
fixed now, yes?

**Comment by MediaSmarts** [comment]
I'm still seeing "PixOne" in both panels after clearing my cache.

**Comment by robgungor** [comment]
fixed for me.
